---
title: 'Final Project'
author: "Devansh Agarwal"
date: 'Due Date: 12/14/2020'
output:
  html_notebook:
    df_print: paged
  html_document:
    df_print: paged
---
### Setup 
```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
# Libraries

library(genius)
library(tidyverse)
library(qdap)
library(tidytext)
library(rvest)

```
### Data Access
```{r}
# Data Scraping

page = "https://en.wikipedia.org/wiki/Grammy_Award_for_Record_of_the_Year"

XPATHgen = "/html/body/div[3]/div[3]/div[5]/div[1]/table"

Music <- data.frame()

for (i in 5:8){ # Loop for each decade
  # Scrape website
  Temp <- page %>% 
    read_html() %>%
    html_nodes(xpath = paste(XPATHgen,'[',i,']',sep = '')) %>%
    html_table(fill = TRUE)
  Music <- rbind(Music,Temp[[1]])
}

rm(Temp,i,page,XPATHgen) # Remove unneeded objects from Environment 
```

### Data Wrangling 

```{r}
# Data Cleaning

MusicCleaned <- 
  Music %>% 
  na.omit() %>% # Remove NAs
  transmute( 
    year = gsub(pattern = '(\\[\\d+\\])',replacement = '',x = `Year[I]`), # Remove foot notes
    track = Record,
    artist = `Artist(s)`
  ) %>%
  mutate(
    decade = paste(substr(year,1,3),'0s',sep = '')
  )

# Add Lyrics 

Lyrics <- 
  MusicCleaned %>%
  add_genius(artist, track, type = "lyrics") # Got 174 songs 

# Convert to words 

Verse_words <- 
  Lyrics %>%
  unnest_tokens(word, lyric)

# Create Data frames for both sets stop words and combine them

words = c("ba","du","yeah","da","ya","ooh","gonna","na","uh","la","hol")

New_Words = data.frame(word = words)

data("stop_words")

Stop_words <-
  stop_words %>%
  select(word)

Stop_words <- rbind(Stop_words,New_Words) 

# Create Dataframe for Verse words without stopped words

Verse_words_Stopped <-
  Verse_words %>%
  anti_join(Stop_words,by = "word")

# Clean environment 

rm(Lyrics,Music,MusicCleaned,New_Words,stop_words,Stop_words,words)

# Write to CSV files

write.csv(Verse_words_Stopped,'Verse_words_Stopped.csv')
write.csv(Verse_words,'Verse_words.csv')
```

### Data Visualization 

#### Graph 1

```{r}
# Read data back in 

Verse_words <- read.csv("Verse_words.csv", sep = ",", header=T)

# Data wrangling for first graph 

Graph1 <- 
  Verse_words %>%
  group_by(track,artist,decade) %>%
  summarise(count = n())

# Graph boxplot

Graph1 %>%
  ggplot(aes(x = decade,y = count,fill = decade)) +
  geom_boxplot() +
  ggtitle("Boxplots of Words per Grammy Nominated Song by Decade") +
  ylab("Words per Song") + 
  xlab("Decade") +
  theme(legend.position = "none")
```
#### Graph 2 

```{r}

Verse_words_Stopped <- read.csv("Verse_words_Stopped.csv", sep = ",", header=T)

Topten <-
  Verse_words_Stopped %>%
  group_by(word) %>%
  summarise(count = n()) %>%
  arrange(desc(count)) %>%
  top_n(10)

Topten %>%
  ggplot(aes(x = reorder(word,-count), y = count)) +
  geom_col(fill = "#A4DF85",color = "black") +
  ggtitle()
  ylab() + 
  xlab

```
#### Graph 3



```{r}

```




